controllers/OrdersController.php
<?php

namespace app\controllers;

use app\models\JobListProduct;
use app\models\JobListSearch;
use app\models\manual\ListServiceProduct;
use app\models\Move;
use app\models\OrderAct;
use app\models\OrderActSearch;
use app\models\Resource;
use Yii;
use app\models\Orders;
use app\models\OrdersSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Clients;
use yii\helpers\ArrayHelper;
use app\models\manual\OrderStatus;
use app\models\JobList;
use yii\data\ActiveDataProvider;
use app\models\manual\ListServices;
use app\models\manual\Product;
use app\models\StatusMessage;
use app\helpers\ChatAPI;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            /*'companies' => [
                'class' => \app\filters\CompaniesFilter::class,
            ],*/
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex($l = 10, $scrollTo = null)
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = false;

        $dataProvider->query->andWhere(['orders.atelier_id' => Yii::$app->user->identity->atelier_id]);


        \Yii::warning($dataProvider->getCount().' '.$l, 'TOTAL COUNT');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'l' => $l,
            'scrollTo' => $scrollTo,
            'enableScroll' => ($dataProvider->getTotalCount() >= $l)
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $tab = 'home-fill')
    {
//        $visualButton = true;
//        $sum = 0;
//        $statusOrder = ArrayHelper::map(OrderStatus::find()->all(), 'id', 'name');
        $model = $this->findModel($id);

//        if ($id > 0)
//        {
//            $query = JobList::find()->where(['order_id'=>$id]);
//            $jobList =JobList::find()->where(['order_id'=>$id])->all();
//            foreach($jobList as $job){$sum += $job->price * $job->count;}   //считаем сумму по заказу
//            if($model->sale > 0)
//            {
//                $discount = ($sum / 100) * $model->sale;
//                $sum = $sum - $discount;
//            }
//            if($model->prepay > 0) $sum = $sum - $model->prepay;
//        }
//        else $query = JobList::find();
//
//        $dataProvider = new ActiveDataProvider([
//            'query' => $query,
//            'sort'=>array(
//                'defaultOrder'=>['id' => SORT_DESC],
//            ),
//            'pagination' => [
//                'pageSize'      => 10,
//                'validatePage'  => false,
//            ],
//
//        ]);
//
//        unset( $statusOrder[3] );
//        if ($model->status_id == 3)  $visualButton = false;
//
//        $contentJob = $this->renderPartial('job', [
//            'title' =>  'Заказ #' .$id,
//            'label' => 'Заказ',
//            'id'    =>$id,
//            'sum'   => $sum,
//            'visualButton'  => $visualButton,
//            'dataProvider'  => $dataProvider,
//            'statusOrder'   => $statusOrder,
//            'model'         => $model,
//        ]);
//
//        $contentOrder = $this->renderPartial('_ajax_view', [
//            'model' => $model,
//            'title' => 'Просмотр заказа',
//            'label' => 'Заказы',
//        ]);


        $jobListSearchModel = new JobListSearch();
        $jobListDataProvider = $jobListSearchModel->search(Yii::$app->request->queryParams);
        $jobListDataProvider->query->andWhere(['order_id' => $id]);
        $jobListDataProvider->pagination = false;

        $orderSearchModel = new OrderActSearch();
        $orderDataProvider = $orderSearchModel->search(Yii::$app->request->queryParams);
        $orderDataProvider->query->andWhere(['order_id' => $id]);
        $orderDataProvider->pagination = false;



        return $this->render('view', [
            'tab' => $tab,
            'jobListSearchModel' => $jobListSearchModel,
            'jobListDataProvider' => $jobListDataProvider,
            'orderSearchModel' => $orderSearchModel,
            'orderDataProvider' => $orderDataProvider,
            'model' => $model,
        ]);
    }

    public function actionNewStatus($idOrder, $newSum, $status_id)
    {
        $model = Orders::findOne($idOrder);
        $model->status_id = $status_id;
        $model->cost = $newSum;
        $model->save();

        $this->redirect(['view','id' => $idOrder]);
    }

    public function actionAddJobOld($id, $job)
    {
        $request = Yii::$app->request;
        $model = new JobList();
        $service = ArrayHelper::map(ListServices::find()->all(), 'id', 'name');
        $products = ArrayHelper::map(Product::find()->all(), 'id', 'name');
        Yii::$app->response->format = Response::FORMAT_JSON;

        if($model->load($request->post()) && $model->save())
        {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'title'=> $job == 'service' ? "Услуги" : "Товары",
                'content'=>'<span class="text-success">Успешно выпольнено</span>',
                'footer'=> Html::button('Ок',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::a('Добавить ещё',['/orders/add-job','id'=>$id,'job' => $job],['class'=>'btn btn-primary','role'=>'modal-remote'])
            ];
        }
        else
        {
            $model->count = 1;
            return [
                'title'=> "Добавить услугу",
                'size' => 'normal',
                'content'=>$this->renderAjax('modals/_form_joblist', [
                    'title' => 'Добавить к заказу: ',
                    'label' => 'Список работ',
                    'id' =>$id,
                    'model' => $model,
                    'service' => $service,
                    'products' => $products,
                    'job' => $job,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
            ];
        }
    }

    public function actionAddJob($id, $job)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $service = ArrayHelper::map(ListServices::find()->all(), 'id', 'name');
        $products = ArrayHelper::map(Product::find()->all(), 'id', 'name');
        Yii::$app->response->format = Response::FORMAT_JSON;

        if($model->load($request->post()) && $model->save())
        {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'title'=> $job == 'service' ? "Услуги" : "Товары",
                'content'=>'<span class="text-success">Успешно выполнено</span>',
                'footer'=> Html::button('Ок',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::a('Добавить ещё',['/orders/add-job','id'=>$id,'job' => $job],['class'=>'btn btn-primary','role'=>'modal-remote'])
            ];
        }
        else
        {
            $model->jobs = JobList::find()->where(['order_id' => $model->id])->asArray()->all();

            $model->acts = ArrayHelper::getColumn(OrderAct::find()->where(['order_id' => $model->id])->all(), 'id');
            $model->acts = OrderAct::find()->where(['order_id' => $model->id])->asArray()->all();


            return [
                'title'=> "Добавить услугу",
                'size' => 'normal',
                'content'=>$this->renderAjax('modals/_form_joblist', [
                    'title' => 'Добавить к заказу: ',
                    'label' => 'Список работ',
                    'id' =>$id,
                    'model' => $model,
                    'service' => $service,
                    'products' => $products,
                    'job' => $job,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::button('Добавить',['class'=>'btn btn-primary','type'=>"submit"])
            ];
        }
    }

    public function actionUpdateJobList($id, $job, $job_id)
    {
        $request = Yii::$app->request;
        $model = JobList::findOne($job_id);
        $service = ArrayHelper::map(ListServices::find()->all(), 'id', 'name');
        $products = ArrayHelper::map(Product::find()->all(), 'id', 'name');
        Yii::$app->response->format = Response::FORMAT_JSON;

        if($model->load($request->post()) && $model->save())
        {
            return [
                'forceReload'=>'#crud-datatable-pjax',
                'forceClose'=>true,
            ];
        }
        else
        {

            return [
                'title'=> "Изменить",
                'size' => 'normal',
                'content'=>$this->renderAjax('modals/_form_joblist', [
                    'title' => 'Добавить к заказу: ',
                    'label' => 'Список работ',

views/orders/_ajax_view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use yii\jui\AutoComplete;
use johnitvn\ajaxcrud\CrudAsset; 
use yii\helpers\Url;
use kartik\range\RangeInput;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;

/*\johnitvn\ajaxcrud\CrudAsset::register($this);*/

?>

<div class="box box-solid box-warning">    
        <div class="box-body">
            <div class="row">

                <?php Pjax::begin(['enablePushState' => false, 'id' => 'order-pjax']) ?>
                    <div class="col-md-12">
                        <h3>
                            Информация по заказу 
                            <?php if($model->status_id != 3){ ?>
                                <a class="btn btn-primary" role="modal-remote" href="<?=Url::toRoute(['edit-order', 'id' => $model->id])?>"><i class="fa fa-pencil"></i></a>
                            <?php } ?> 
                        </h3>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('status_id')?></b></td>
                                        <td><?=Html::encode($model->status->name)?></td>
                                        <td><b><?=$model->getAttributeLabel('cost')?></b></td>
                                        <td><?=Html::encode($model->cost == null ? '0' : \Yii::$app->formatter->asDecimal($model->cost,0))?></td>
                                        <td><b><?=$model->getAttributeLabel('order_type')?></b></td>
                                        <td><?=Html::encode($model->getOrderTypeDescription())?></td>
                                        <td><b><?=$model->getAttributeLabel('pollution_id')?></b></td>
                                        <td><?=Html::encode($model->pollution->name)?></td>
                                    </tr>

                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('clothes_type')?></b></td>
                                        <td><?=Html::encode($model->clothesType->name)?></td>
                                        <td><b><?=$model->getAttributeLabel('prepay')?></b></td>
                                        <td><?=Html::encode($model->prepay == null ? '0' : \Yii::$app->formatter->asDecimal($model->prepay,0))?></td>
                                        <td><b><?=$model->getAttributeLabel('spot_id')?></b></td>
                                        <td><?=Html::encode($model->spot->name)?></td>
                                        <td><b><?=$model->getAttributeLabel('lost_product')?></b></td>
                                        <td><?=Html::encode($model->lost_product)?></td>
                                    </tr>

                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('user_id')?></b></td>
                                        <td><?=Html::encode($model->user->name)?></td>
                                        <td><b><?=$model->getAttributeLabel('sale')?></b></td>
                                        <td><?=Html::encode($model->sale)?></td>
                                        <td><b><?=$model->getAttributeLabel('marketing_id')?></b></td>
                                        <td><?=Html::encode($model->marketing->name)?></td>
                                        <td><b><?=$model->getAttributeLabel('issue_date')?></b></td>
                                        <td><?=($model->issue_date)?></td>
                                    </tr>

                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('marks_id')?></b></td>
                                        <td><?=Html::encode($model->marks->name)?></td>
                                        <td><b><?=$model->getAttributeLabel('quick')?></b></td>
                                        <td><?=Html::encode($model->quick == 1 ? 'Да' : 'Нет')?></td>
                                        <td><b><?=$model->getAttributeLabel('creator_id')?></b></td>
                                        <td><?=Html::encode($model->creator->name)?></td>
                                        <td><b><?=$model->getAttributeLabel('fact_date')?></b></td>
                                        <td><?=$model->fact_date?></td>
                                    </tr>

                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('comment')?></b></td>
                                        <td colspan="7"><?=Html::encode($model->comment)?></td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php Pjax::end() ?>


                <?php Pjax::begin(['enablePushState' => false, 'id' => 'detail-pjax']) ?>
                    <div class="col-md-7">
                        <h3>Детальность 
                            <?php if($model->status_id != 3){ ?>
                            <a class="btn btn-primary" role="modal-remote" href="<?=Url::toRoute(['edit-detail', 'id' => $model->id])?>"><i class="fa fa-pencil"></i></a>
                            <?php } ?>
                        </h3>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('color')?></b></td>
                                        <td><?=Html::encode($model->color)?></td>
                                        <td><b><?=$model->getAttributeLabel('fabric_structure')?></b></td>
                                        <td><?=Html::encode($model->fabric_structure)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('hidden_defect')?></b></td>
                                        <td><?=Html::encode($model->hidden_defect == 1 ? 'Да' : 'Нет')?></td>
                                        <td><b><?=$model->getAttributeLabel('symbol')?></b></td>
                                        <td><?=Html::encode($model->symbol)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('product_warranty')?></b></td>
                                        <td><?=Html::encode($model->product_warranty)?></td>
                                        <td><b><?=$model->getAttributeLabel('complekt')?></b></td>
                                        <td><?=Html::encode($model->complekt)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('defect')?></b></td>
                                        <td><?=Html::encode($model->defect)?></td>
                                        <td><b><?=$model->getAttributeLabel('damage')?></b></td>
                                        <td><?=Html::encode($model->damage)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('spots_location')?></b></td>
                                        <td><?=Html::encode($model->spots_location)?></td>
                                        <td><b><?=$model->getAttributeLabel('wear')?></b></td>
                                        <td><?=Html::encode($model->wear)?></td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"><b><?=$model->getAttributeLabel('material')?></b></td>
                                        <td colspan="2"><?=Html::encode($model->material)?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php Pjax::end() ?>

                <?php Pjax::begin(['enablePushState' => false, 'id' => 'client-pjax']) ?>
                    <div class="col-md-5">
                        <h3>Информации по клиентам 
                            <?php if($model->status_id != 3){ ?>
                                <a class="btn btn-primary" role="modal-remote" href="<?=Url::toRoute(['edit-client', 'id' => $model->client_id])?>"><i class="fa fa-pencil"></i></a>
                            <?php } ?>
                        </h3>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('client_id')?></b></td>
                                        <td><?=Html::encode($model->client->fio)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('telephone')?></b></td>
                                        <td><?=Html::encode($model->telephone)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('client.group_id')?></b></td>
                                        <td><?=Html::encode($model->client->group->name)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('client.sale_for_product')?></b></td>
                                        <td><?=Html::encode($model->client->sale_for_product)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('client.sale_for_work')?></b></td>
                                        <td><?=Html::encode($model->client->sale_for_work)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?=$model->getAttributeLabel('client.usd_ball')?></b></td>
                                        <td><?=Html::encode($model->client->usd_ball)?></td>
                                    </tr>
                                    <!-- <tr>
                                        <td><b><?php //$model->getAttributeLabel('client.email')?></b></td>
                                        <td><?php //Html::encode($model->client->email)?></td>
                                    </tr>
                                    <tr>
                                        <td><b><?php //$model->getAttributeLabel('client.address')?></b></td>
                                        <td><?php //Html::encode($model->client->address)?></td>
                                    </tr> -->
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php Pjax::end() ?>

            </div>
        </div>
</div>

<?php 
$this->registerJs(<<<JS
    $('#type').on('change', function() 
    {  
        var type = this.value; //console.log(type);
        $('#comp').hide();
        if(type == 2) $('#comp').show(); 
    }
);
JS
);
?>
<?php 
$this->registerJs(<<<JS
    $('#order_type').on('change', function() 
    {  
        var type = this.value;
        $('#polis').hide();
        if(type == 7) $('#polis').show(); 
    }
);
JS
);
?>

views/orders/apply_status.php
<?php

use app\models\Users;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="job-list-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status_id')->widget(Select2::class, [
        'data' => ArrayHelper::map(\app\models\manual\OrderStatus::find()->orderBy('sort')->all(), 'id', 'name'),
    ]) ?>

    <?php ActiveForm::end(); ?>

</div>

views/orders/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Orders */
$this->title = '';
?>
<div class="orders-create">
	<?php if( $model->step == 1) { ?>

	    <?= $this->render('_form_base', [
	        'model' => $model,
	    ]) ?>

	<?php } if( $model->step == 2) { ?>

		<?= $this->render('_form_additional', [
	        'model' => $model,
	    ]) ?>

	<?php } ?>
</div>

views/orders/job.php
<?php
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ButtonDropdown;
use app\models\manual\ListServices;
use app\models\manual\Product;

?>
<div class="job-list-index">

        <?php if($visualButton){?>
			<div class="row">
				<div class="col-md-2">
					<h2>
						<?=Html::encode($title)?>
					</h2>
				</div>
				<div class="col-md-2">
					<h2>
						<?=Html::activeDropDownList(
							$model, 
							'status_id', 
							$statusOrder, 
							[
								'prompt' => 'Определить статус','class' => 'form-control',
								'onchange' =>'window.location.href = "/orders/new-status?idOrder='.$id.'&newSum='.$sum.'&status_id="+$(this).val();'
							]
						)?>
					</h2>
				</div>
			</div>
		<br/>
		<?php } ?>	
		<div class="row">
			<?php	if($visualButton){ ?>
				<div class="col-xs-6 col-sm-2">
					<?=Html::a('Добавить услугу', ['/orders/add-job', 'id'=>$id, 'job' => 'service'],['role'=>'modal-remote','title'=> 'Добавить услугу','class'=>'btn btn-success'])?>
				</div>	

				<div class="col-xs-6 col-sm-2">
					<?=Html::a('Добавить товар', ['/orders/add-job', 'id'=>$id, 'job' => 'parts'],['role'=>'modal-remote','title'=> 'Добавить товар','class'=>'btn btn-success'])?>
				</div>
			<?php }	 ?>

				<div class="col-xs-6 col-sm-2">
					<?=ButtonDropdown::widget([
						'label' => 'Печатать',
						'options' => [
							'target'=>'_blank',
							'class' => 'btn-info',
							'style' => 'margin:2px',
							],
							'dropdown' => [
							'items' => [
								[
									'label' => 'БСО',
									'url' => ['print-bso','id' => $id],
									'linkOptions' => ['target'=>'_blank'],
								],
								[
									'label' => 'Квитанции-договора',
									'url' =>['print-contract','id' => $id],
									'linkOptions' => ['target'=>'_blank'],
								],
								/*[
									'label' => 'Форму заказа',
									'url' =>['print-order','id' => $id],
									'linkOptions' => ['target'=>'_blank'],
								],*/
							]
						]	
					])?>
				</div>
			 
		</div>
		<br/>
			
		<?php
			if($visualButton && $dataProvider->getCount() > 0){	?>
			<div class="row">
				<div class="col-xs-6 col-sm-2">
					<?=Html::a(' Завершить заказ', [ 'new-status', 'idOrder'=>$id , 'newSum' =>$sum, 'status_id' => 3, ], ['class' => 'btn btn-danger',])?>
				</div>			
		 	</div>	
		 <?php } ?>	
	
	<?php Pjax::begin(['enablePushState' => false, 'id' => 'crud-datatable-pjax']) ?>
		<?= GridView::widget([
	        'dataProvider' => $dataProvider,
	      	'columns' => [
	            ['class' => 'yii\grid\SerialColumn'],

				[
					'attribute'=>'id',
					'content'=>function ($data){
						return '<span class="label label-warning" style="font-size:13px;">'.Html::a($data->id.'   ', ['/orders/update-job-list','id'=>$data->order_id, 'job' => $data->type, 'job_id' => $data->id], ['style'=>'color:#ffffff;', 'role'=>'modal-remote',]).'</span>';
					},
				],
	            //'order_id',
				[
					'attribute' => 'job_name',				
					'label' => 'Работа',	
					'value'=>'job.name', 
					'content'=>function ($data){   
						if($data->type == 'service'){
							$service = ListServices::findOne($data->job_id);
							return $service->name;
						}  
						else { 
							$product = Product::findOne($data->job_id);
							return $product->name;
						}
				 	},
				],
	            'count',
	            'price',
	            [
	            	'class' => 'yii\grid\ActionColumn',
					'template' => '{delete}',
					'buttons' => [
		               'delete' => function ($url, $model, $key){ 
						if($model->order->status_id != 3){
							return Html::a('<span class="glyphicon glyphicon-trash"></span>', 
								['/orders/job-list-delete','id'=>$key, 'order_id' => $model->order_id],
								[
									'title'=>'Удалить',
									'aria-label'=>'Удалить',
									'data-confirm'=>'Вы уверены, что хотите удалить этот элемент?',
									'data-method'=>'post',
								]
							);
						}
		              }, 
						
		            ],
				],
	        ],
	    ]); ?>	
	<h3><?php echo Html::encode('Итого : '.\Yii::$app->formatter->asDecimal($sum,0)  . "   (Сумма  с учетом скидки и предоплаты)"); ?></h3>
	
	<?php Pjax::end(); ?>
									
</div>

views/orders/update-job-product.php
<?php
use app\models\manual\Product;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\manual\ListServices */
/* @var $form yii\widgets\ActiveForm */


if($model->isNewRecord == false){
//    $model->productList = ArrayHelper::getColumn(\app\models\JobListProduct::find()->where(['job_list_id' => $model->id])->all(), 'id');
    $model->productList = \app\models\JobListProduct::find()->where(['job_list_id' => $model->id])->asArray()->all();
}

$items = [];

/** @var Product[] $products */
$products = Product::find()->all();

foreach ($products as $product)
{
    $unitLabel = '';

    if($product->unit !== null){
        $unitLabel = ' ('.ArrayHelper::getValue(Product::unitLabels(), $product->unit).')';
    }

    $items[$product->id] = $product->name.$unitLabel;
}



?>

<div class="list-services-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'productList')->widget(\unclead\multipleinput\MultipleInput::class, [
                'id' => 'my_id',
                'addButtonOptions' => [
                    'class' => 'btn btn-sm btn-primary btn-my-square',
                    'label' => '+',
                ],
                'removeButtonOptions' => [
                    'class' => 'btn btn-sm btn-danger btn-my-square',
                    'label' => 'x',
                ],
                'min' => 0,
                'columns' => [
                    [
                        'name' => 'id',
                        'options' => [
                            'type' => 'hidden'
                        ]
                    ],
                    [
                        'name'  => 'product_id',
                        'title' => 'Расходники',
                        'options' => [
                            'class' => 'input-priority',
                        ],
                        'headerOptions' => [
                            'style' => 'width: 80%;',
                        ],
                        'type'  => 'dropDownList',
                        'enableError' => true,
                        'items' => $items,
                    ],
                    [
                        'name'  => 'count',
                        'title' => 'Объем',
                        'enableError' => true,
                        'options' => [
                            'class' => 'input-priority',
                        ],
                        'headerOptions' => [
                            'style' => 'width: 20%;',
                        ]
                    ],
                ],
            ])->label(false); ?>
        </div>
    </div>



    <?php if (!Yii::$app->request->isAjax){ ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Cоздать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>